# as usual, we will perform some basic tests && ensure that our distro's ready to work with us!

- name: "Base server's setup"
  hosts: <group> # according by your needs!
#  remote_user: root # our default user
  remote_user: <user> # our previously configured user
  vars:
    ansible_port: <port> # default port you have previously configured!
#    ansible_port: 22 # default port to connect to
#    ansible_port: 1984 # default port to connect to

- name: "Hey OP! Here I come!"
  mattermost:
    url: 'https://<your_server>.wtf' #¯\_(ツ)_/¯
    api_key: '<api_key>'
    text: "{{ ansible_hostname }} ({{ inventory_hostname }}) is deploying !"

- name: Ping before OPS
    ping:

  roles:
    - common_config
